[template]
src = "postgres.env.tmpl"
dest = "/etc/profile.d/postgres.sh"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/Database"
]

reload_cmd="/usr/local/bin/nubis-purpose db-monitor-postgres && /usr/bin/systemctl restart postgres_exporter || true"
